### ISSUE TITLE
Adding Local Administrators to Windows Not Possible

### ISSUE THREAD

**Issue by fresher-unnamed-0b** [bbmumford/Intune-Toolkit#2]
Brilliant repo! 

I’ve been trying to follow the steps on your guide to adding local administrators to Windows but have hit a roadblock. I am doing the following:

_New Profile > Templates > Endpoint Protection > Accounts._ 

I do not see a section here to specify usernames or passwords, do you know this to still be possible?

**Comment by bbmumford** [comment]
Thanks for the feedback.

It seems that creating a local account via Intune's Endpoint protection profile is no longer applicable. 
In July 2024, Microsoft deprecated certain Intune profiles, including those under Endpoint protection, and introduced a consolidated Account protection profile within the Endpoint security node.

Thank you for bringing the change to my attention, i will update the documentation to replace it to use Custom OMA-URI Configuration Profile settings.
